[package]
name = "planet-derive"
version = "0.1.0"
authors = ["Dave Remy <email@daveremy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = "0.15.23"
quote = "0.6.10"